curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JAN14 -o JAN14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/FEB14 -o FEB14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAR14 -o MAR14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/APR14 -o APR14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAY14 -o MAY14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUN14 -o JUN14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUL14 -o JUL14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/AUG14 -o AUG14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/SEP14 -o SEP14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/OCT14 -o OCT14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/NOV14 -o NOV14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/DEC14 -o DEC14.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JAN15 -o JAN15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/FEB15 -o FEB15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAR15 -o MAR15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/APR15 -o APR15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAY15 -o MAY15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUN15 -o JUN15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUL15 -o JUL15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/AUG15 -o AUG15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/SEP15 -o SEP15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/OCT15 -o OCT15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/NOV15 -o NOV15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/DEC15 -o DEC15.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JAN16 -o JAN16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/FEB16 -o FEB16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAR16 -o MAR16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/APR16 -o APR16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAY16 -o MAY16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUN16 -o JUN16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUL16 -o JUL16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/AUG16 -o AUG16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/SEP16 -o SEP16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/OCT16 -o OCT16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/NOV16 -o NOV16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/DEC16 -o DEC16.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JAN17 -o JAN17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/FEB17 -o FEB17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAR17 -o MAR17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/APR17 -o APR17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAY17 -o MAY17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUN17 -o JUN17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUL17 -o JUL17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/AUG17 -o AUG17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/SEP17 -o SEP17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/OCT17 -o OCT17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/NOV17 -o NOV17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/DEC17 -o DEC17.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JAN18 -o JAN18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/FEB18 -o FEB18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAR18 -o MAR18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/APR18 -o APR18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAY18 -o MAY18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUN18 -o JUN18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUL18 -o JUL18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/AUG18 -o AUG18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/SEP18 -o SEP18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/OCT18 -o OCT18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/NOV18 -o NOV18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/DEC18 -o DEC18.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JAN19 -o JAN19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/FEB19 -o FEB19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAR19 -o MAR19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/APR19 -o APR19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAY19 -o MAY19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUN19 -o JUN19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JUL19 -o JUL19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/AUG19 -o AUG19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/SEP19 -o SEP19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/OCT19 -o OCT19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/NOV19 -o NOV19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/DEC19 -o DEC19.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/JAN20 -o JAN20.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/FEB20 -o FEB20.txt
curl https://previewsworld.com/Catalog/CustomerOrderForm/TXT/MAR20 -o MAR20.txt
